;=============================================================================
; POLYBAR CONFIGURATION
;=============================================================================

[misc]
padding = 8px

[colors]
background = #2E3440
background-alt = #3B4252
foreground = #ECEFF4
foreground-alt = #D8DEE9
primary = #88C0D0
secondary = #81A1C1
alert = #BF616A
success = #A3BE8C
warning = #EBCB8B

[bar/main]
width = 100%
height = 32
radius = 0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3
line-color = ${colors.primary}

border-size = 0
border-color = #00000000

padding-left = 1
padding-right = 1

module-margin-left = 0
module-margin-right = 0

font-0 = "JetBrains Mono:size=10;2"
font-1 = "Symbols Nerd Font:style=Regular"
font-2 = "Symbols Nerd Font Mono:style=Regular"

modules-left = i3 xwindow
modules-center = 
modules-right = pulseaudio memory cpu wlan battery date my-text-label

tray-position = left
tray-padding = 2

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
separator = ""

[bar/main]
monitor = ${env:MONITOR}

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

label-mode-padding = 2
label-mode-foreground = ${colors.foreground}
label-mode-background = ${colors.primary}

; focused = Active workspace on focused monitor
label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-padding = 2

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

[module/xwindow]
type = internal/xwindow
label = %title:0:50:...%
label-padding = ${misc.padding}

[module/cpu]
type = internal/cpu
interval = 2
warn-percentage = 80

ramp-load-0 = ▁
ramp-load-1 = ▂
ramp-load-2 = ▃
ramp-load-3 = ▄
ramp-load-4 = ▅
ramp-load-5 = ▆
ramp-load-6 = ▇
ramp-load-7 = █

label =  %percentage%%
format =  <label> <ramp-load>
format-background = ${colors.foreground}
format-foreground = ${colors.background}
format-padding = ${misc.padding}
label-warn =  %percentage%%
format-warn = <label-warn> <ramp-load>
format-warn-background = ${colors.alert}
format-warn-padding = ${misc.padding}

[module/memory]
type = internal/memory
interval = 2
warn-percentage = 85

ramp-used-0 = ▁
ramp-used-1 = ▂
ramp-used-2 = ▃
ramp-used-3 = ▄
ramp-used-4 = ▅
ramp-used-5 = ▆
ramp-used-6 = ▇
ramp-used-7 = █

label =  %percentage_used%%
format = <label> <ramp-used>
format-background = ${colors.secondary}
format-foreground = ${colors.background}
format-padding = ${misc.padding}
label-warn =  %percentage_used%%
format-warn = <label-warn> <ramp-used>
format-warn-background = ${colors.alert}
format-warn-padding = ${misc.padding}

[module/wlan]
; 󰢿󰢼󰢽󰢾
type = internal/network
interface-type = wireless
interval = 3.0

ramp-signal-0 = 󰢿
ramp-signal-1 = 󰢼
ramp-signal-2 = 󰢽
ramp-signal-3 = 󰢾

label-connected = %essid% 󰕒 %upspeed% 󰇚 %downspeed%
format-connected = <ramp-signal> <label-connected> 
format-connected-padding = ${misc.padding}
format-connected-background = ${colors.success}
format-connected-foreground = ${colors.background}

label-disconnected = 󰞃 %essid% 󰕒 %upspeed% 󰇚 %downspeed%
format-disconnected = <label-disconnected>
format-disconnected-padding = ${misc.padding}
format-disconnected-background = ${colors.alert}
format-disconnected-foreground = ${colors.foreground}

[module/date]
type = internal/date
interval = 1

date = %Y-%m-%d
time = %H:%M:%S

label =  %date% %time%
format = <label>
; format-background = ${colors.alert}
; format-foreground = ${colors.foreground}
format-padding = ${misc.padding}

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = false
click-right = pavucontrol

format-volume = <label-volume>
format-volume-background = ${colors.primary}
format-volume-foreground = ${colors.background}
format-volume-padding = ${misc.padding}
label-volume = 󰓃 %percentage%%

format-muted = <label-muted>
format-muted-background = ${colors.alert}
format-muted-foreground = ${colors.background-alt}
format-muted-padding = ${misc.padding}
label-muted = 󰓄 %percentage%%

[module/battery]
; battery icons: 󰂎󱊡󱊢󱊣
type = internal/battery
battery = BAT0
adapter = ADP1
full-at = 90
low-at = 20

; bar-capacity-width = 10

ramp-capacity-0 = 󰂎
ramp-capacity-1 = 󱊡
ramp-capacity-2 = 󱊢
ramp-capacity-3 = 󱊣

animation-low-0 = 󰂎
animation-low-1 = 󱊡
animation-low-framerate = 750
format-low = <animation-low> <label-low>
format-low-background = ${colors.alert}
format-low-foreground = ${colors.foreground}
format-low-padding = ${misc.padding}
label-low = %percentage_raw%%

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-background = ${colors.background-alt}
format-discharging-foreground = ${colors.foreground}
format-discharging-padding = ${misc.padding}
label-discharging = %percentage%%

animation-charging-0 = 󰂎
animation-charging-1 = 󱊡
animation-charging-2 = 󱊢
animation-charging-3 = 󱊣
animation-charging-framerate = 750
format-charging = <animation-charging> <label-charging>
format-charging-background = ${colors.primary}
format-charging-foreground = ${colors.background}
format-charging-padding = ${misc.padding}
label-charging = %percentage%%

; animation-full-0 = 󱊣
; animation-full-1 = 󰂎
; animation-full-2 = 󱊣
; animation-full-framerate = 750
format-full = <ramp-capacity> <label-full> 
format-full-background = ${colors.success}
format-full-foreground = ${colors.background}
format-full-padding = ${misc.padding}
label-full = %percentage_raw%%

[module/my-text-label]
type = custom/text

format = <label>
format-background = ${colors.alert}
format-foreground = ${colors.foreground}
format-padding = ${misc.padding}

label = 

click-left = ~/.config/rofi/scripts/powermenu.sh

[settings]
screenchange-reload = true

[global/wm]
margin-top = 5
margin-bottom = 5